[package]
name = "webring_manager_prev"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.17.0"
lambda_http = "0.10.0"
tokio = { version = "1", features = ["macros"] }
